allowBuilds:
  '@robinbobin/eslint-config': false
  '@robinbobin/eslint-config-react': false
  '@robinbobin/eslint-config-react-native': true
  '@robinbobin/prettier-config': true
  '@robinbobin/ts-config': true
  unrs-resolver: true
